---
- name: Add Debian Bullseye repository for libssl1.1
  ansible.builtin.deb822_repository:
    name: bullseye
    types: deb
    uris: http://deb.debian.org/debian
    suites: bullseye
    components: main
    state: present

- name: Install libssl1.1 from bullseye
  ansible.builtin.apt:
    name: libssl1.1
    state: present
    update_cache: true

# skip idempotence tests
- name: Include Mongos install role
  ansible.builtin.include_role:
    name: mongos
  when: "'molecule-idempotence-notest' not in ansible_skip_tags"
